version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
      python: 3.7
  pre_build:
    commands:
      - pip install -r requirements.txt
      - pytest
  build:
    commands:
      - echo No need to build any code.

artifacts:
  files:
    - '**/*'
  name: python-app-$(date +%y%m%d%H%M).zip
